name: Renv
channels:
  - R
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-doParallel
  - r-devtools
  - r-vcfR
  - r-doMC
  - bioconductor-biomart
  #- devtools:
  #   - git+https://github.com/knausb/vcfR